#ifndef WEBSERVERINCLUDE_H_
#define WEBSERVERINCLUDE_H_

#define SERVER_PORT "8080"
#define SERVER_MAX_CONNECTIONS 100
#define MAX_FILE_SIZE 2048
#define MAX_BUFFER_SIZE 4096
#define THREAD_POOL_SIZE 35

#endif